version: '3.1'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    volumes:
      - jenkins_home:/var/jenkins_home:z
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - cdnet
    secrets:
      - host_ssh_key
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - cdnet
  webapp:
    image: himself12794/angular-web-app:latest
    networks:
      - cdnet

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa.pub

networks:
  cdnet:
    driver: bridge

volumes:
  jenkins_home:
  
